name: ideaapp
description: A new Flutter application.
version: 1.1.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.0
  settings_ui: ^0.6.0
  font_awesome_flutter: ^8.5.0
  rxdart: ^0.25.0
  shared_preferences: ^2.0.0
  provider: ^4.0.0
  http: ^0.13.0
  url_launcher:

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/

  fonts:
    - family: Raleway
      fonts:
        - asset: assets/fonts/Raleway-Black.ttf
    - family: RalewayLight
      fonts:
        - asset: assets/fonts/Raleway-Light.ttf
    - family: RalewatMedium
      fonts:
        - asset: assets/fonts/Raleway-Medium.ttf
